
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.supplements': 'Supplements',
    'nav.ai_consultant': 'AI Consultant',
    'nav.blog': 'Blog',
    'nav.affiliate': 'Affiliate',
    'nav.about': 'About',
    'nav.sign_in': 'Sign In',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    
    // AI Consultant Page
    'ai.title': 'AI Supplement',
    'ai.subtitle': 'Consultant',
    'ai.description': 'Get personalized supplement recommendations based on your health goals and needs. Our AI consultant will help you find the perfect products for your wellness journey.',
    'ai.consultant_name': 'AI Consultant',
    'ai.consultant_subtitle': 'Personalized supplement selection',
    'ai.input_placeholder': 'Describe your needs...',
    'ai.initial_message': 'Hello! I will help you find the perfect supplements for your needs. Tell me about your health problems or goals you want to achieve?',
    
    // Footer
    'footer.brand_description': 'Leading provider of high-quality natural dietary supplements for better health for you and your family',
    'footer.quick_links': 'Quick Links',
    'footer.all_products': 'All Products',
    'footer.categories': 'Categories',
    'footer.affiliate_program': 'Affiliate Program',
    'footer.about_us': 'About Us',
    'footer.customer_service': 'Customer Service',
    'footer.faq': 'FAQ',
    'footer.return_policy': 'Return Policy',
    'footer.shipping': 'Shipping',
    'footer.contact_us': 'Contact Us',
    'footer.copyright': '© 2024 SIAM HEALTHY. All rights reserved',
    
    // Home Page
    'home.hero_title': 'SIAM HEALTHY',
    'home.hero_subtitle': 'Premium Natural Supplements',
    'home.ai_recommendations_title': 'Get Personalized Recommendations',
    'home.ai_recommendations_description': 'Our AI consultant analyzes your health goals and recommends the perfect supplements for your needs. Get expert guidance in finding the right products for your wellness journey.',
    'home.ai_personal_selection': 'Personal Selection',
    'home.ai_goal_matching': 'Goal-Based Matching',
    'home.ai_instant_recommendations': 'Instant Recommendations',
    'home.start_ai_consultation': 'Start AI Consultation',
    'home.shop_supplements': 'Shop Supplements',
    'home.product_categories': 'Product Categories',
    'home.categories_description': 'Choose a category that matches your health needs',
    'home.featured_products': 'Featured Products',
    'home.featured_description': 'High-quality products popular among our customers',
    'home.all_products': 'All Products',
    'home.latest_insights': 'Latest Health Insights',
    'home.insights_description': 'Expert advice from nutritionists, doctors, and wellness practitioners',
    'home.view_all_posts': 'View All Posts',
    'home.view': 'View',
    'home.buy': 'Buy',
    'home.read': 'Read',
    
    // Categories
    'categories.beauty': 'Beauty and Anti-Aging Care',
    'categories.beauty_desc': 'Skin brightening and anti-aging support',
    'categories.weight': 'Weight Control and Body Shaping',
    'categories.weight_desc': 'Fat burning and metabolism support',
    'categories.vision': 'Eye Health and Vision',
    'categories.vision_desc': 'Vision support and eye protection',
    'categories.heart': 'Heart Health',
    'categories.heart_desc': 'Blood pressure and cardiovascular system support',
    'categories.detox': 'Detox and Cleansing',
    'categories.detox_desc': 'Body cleansing and toxin removal',
    
    // Products Page
    'products.title': 'Natural Health Supplements',
    'products.description': 'Discover our premium collection of natural dietary supplements',
    'products.search_placeholder': 'Search products...',
    'products.filter_category': 'Filter by Category',
    'products.all_categories': 'All Categories',
    'products.sort_by': 'Sort by',
    'products.price_low_high': 'Price: Low to High',
    'products.price_high_low': 'Price: High to Low',
    'products.newest': 'Newest First',
    'products.popularity': 'Most Popular',
    'products.no_products': 'No products found',
    'products.no_products_desc': 'Try adjusting your search or filter criteria',
    'products.clear_filters': 'Clear Filters',
    'products.add_to_cart': 'Add to Cart',
    'products.view_details': 'View Details',
    'products.reviews': 'reviews',
    
    // Cart Page
    'cart.title': 'Shopping Cart',
    'cart.empty_title': 'Your cart is empty',
    'cart.empty_description': 'Add products to your cart to continue shopping',
    'cart.continue_shopping': 'Continue Shopping',
    'cart.clear_cart': 'Clear Cart',
    'cart.cart_items': 'Cart Items',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Delivery',
    'cart.total': 'Total',
    'cart.free_delivery': 'Free Delivery',
    'cart.checkout': 'Proceed to Checkout',
    'cart.shipping_info': 'Shipping Information',
    'cart.first_name': 'First Name',
    'cart.last_name': 'Last Name',
    'cart.email': 'Email',
    'cart.phone': 'Phone',
    'cart.address': 'Address',
    'cart.city': 'City',
    'cart.postal_code': 'Postal Code',
    'cart.country': 'Country',
    'cart.payment_method': 'Payment Method',
    'cart.delivery_method': 'Delivery Method',
    'cart.standard_delivery': 'Standard Delivery',
    'cart.express_delivery': 'Express Delivery',
    'cart.pickup': 'Pickup',
    'cart.place_order': 'Place Order',
    'cart.required': 'required',
    
    // About Page
    'about.hero_title': 'Your Trusted Partner',
    'about.hero_subtitle': 'in Natural Health',
    'about.hero_description': 'We are specialists in natural dietary supplements committed to providing high-quality products for better health for you and your family. With over 5 years of experience',
    'about.mission_title': 'Our Mission',
    'about.mission_description': 'To provide high-quality natural dietary supplements that are safe, effective, and accessible to help everyone achieve better health and quality of life',
    'about.vision_title': 'Our Vision',
    'about.vision_description': 'To be the most trusted natural supplement brand in Thailand and expand to international markets in the future, following sustainable development principles',
    'about.values_title': 'Our Values',
    'about.values_description': 'Principles and values that form the foundation of our work and service',
    'about.natural_title': '100% Natural',
    'about.natural_description': 'We only use high-quality natural ingredients, free from harmful chemicals',
    'about.standards_title': 'International Standards',
    'about.standards_description': 'All products are certified with GMP, FDA and ISO standards',
    'about.care_title': 'Customer Care',
    'about.care_description': 'We understand each customer\'s needs and strive to provide the best service',
    'about.expert_title': 'Expert Team',
    'about.expert_description': 'Knowledgeable team in nutrition and health ready to provide consultation',
    'about.achievements_title': 'Achievements We\'re Proud Of',
    'about.achievements_description': 'Numbers that reflect our success and customer trust',
    'about.customers': 'Satisfied Customers',
    'about.experience': 'Years Experience',
    'about.products_count': 'Quality Products',
    'about.satisfaction': 'Satisfaction Rate',
    'about.certifications_title': 'Standard Certifications',
    'about.certifications_description': 'Our products are certified by trusted organizations',
    'about.journey_title': 'Our Growth Journey',
    'about.journey_description': 'Our history and progress over the years',
    'about.why_choose_title': 'Why Choose Us',
    'about.why_choose_description': 'Reasons why over 10,000 customers trust us',
    'about.trusted_quality': 'Trusted Quality',
    'about.trusted_quality_desc': 'Every product undergoes strict quality control and is certified to international standards',
    'about.fast_delivery': 'Fast Delivery Service',
    'about.fast_delivery_desc': 'Free nationwide delivery, guaranteed delivery within 1-2 business days with package tracking service',
    'about.expert_consultation': 'Expert Team Ready to Consult',
    'about.expert_consultation_desc': 'Pharmacists and nutritionists ready to provide product selection advice 24 hours a day',
    'about.cta_title': 'Ready to Start Your Health Journey With Us?',
    'about.cta_description': 'Join the SIAM HEALTHY family and experience natural health care',
    'about.shop_products': 'Shop Products',
    'about.join_affiliate': 'Join Affiliate Program',
    
    // Affiliate Page
    'affiliate.hero_title': 'Become Our Partner',
    'affiliate.hero_description': 'Share natural supplements you believe in and earn up to 25% commission on every sale.',
    'affiliate.start_earning': 'Start Earning Today - It\'s Free!',
    'affiliate.why_partner_title': 'Why Partner With Us?',
    'affiliate.benefits_description': 'Everything you need to succeed as our affiliate partner',
    'affiliate.high_commission': 'High Commission',
    'affiliate.high_commission_desc': 'Earn up to 25% on every sale you make',
    'affiliate.full_support': 'Full Support',
    'affiliate.full_support_desc': 'Get help from our dedicated team',
    'affiliate.free_products': 'Free Products',
    'affiliate.free_products_desc': 'Receive samples to test and review',
    'affiliate.how_it_works': 'How It Works',
    'affiliate.steps_description': 'Get started in 3 simple steps',
    'affiliate.step_apply': 'Apply',
    'affiliate.step_apply_desc': 'Fill out the simple form below',
    'affiliate.step_approved': 'Get Approved',
    'affiliate.step_approved_desc': 'We\'ll review and approve within 2 days',
    'affiliate.step_earn': 'Start Earning',
    'affiliate.step_earn_desc': 'Share your links and earn money',
    'affiliate.join_program': 'Join Our Partner Program',
    'affiliate.join_description': 'Ready to start earning? It takes less than 2 minutes.',
    'affiliate.your_name': 'Your Name',
    'affiliate.email_address': 'Email Address',
    'affiliate.promote_where': 'Where will you promote?',
    'affiliate.choose_platform': 'Choose your platform',
    'affiliate.agree_terms': 'I agree to the Terms and Conditions',
    'affiliate.submit_application': 'Submit Application',
    'affiliate.submitting': 'Submitting...',
    'affiliate.quick_questions': 'Quick Questions',
    'affiliate.how_much_earn': 'How much can I earn?',
    'affiliate.how_much_earn_answer': 'You earn up to 25% commission on every sale. The more you sell, the higher your rate.',
    'affiliate.when_paid': 'When do I get paid?',
    'affiliate.when_paid_answer': 'Commissions are paid monthly on the 15th, directly to your bank account.',
    'affiliate.really_free': 'Is it really free?',
    'affiliate.really_free_answer': 'Yes! There are no fees to join. You start earning immediately after approval.',
    
    // Blog Page
    'blog.title': 'Health & Wellness Blog',
    'blog.description': 'Expert insights on healthy living, disease prevention, and natural wellness from nutritionists, doctors, and traditional medicine practitioners.',
    'blog.all': 'All',
    'blog.read_more': 'Read More',
    'blog.min_read': 'min read',
    'blog.back_to_blog': 'Back to Blog',
    'blog.related_articles': 'Related Articles',
    'blog.post_not_found': 'Post Not Found',
    'blog.post_not_found_desc': 'The blog post you\'re looking for doesn\'t exist.',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.personal_info': 'Personal Information',
    'profile.order_history': 'Order History',
    'profile.settings': 'Settings',
    'profile.save_changes': 'Save Changes',
    'profile.no_orders': 'No orders yet',
    'profile.no_orders_desc': 'Start shopping to see your orders here',
    
    // Auth Page
    'auth.sign_in': 'Sign In',
    'auth.sign_up': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.no_account': 'Don\'t have an account?',
    'auth.have_account': 'Already have an account?',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.page': 'Page',
    'common.of': 'of',
    'common.items': 'items',
    'common.item': 'item',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.discount': 'Discount',
    'common.free': 'Free',
    'common.new': 'New',
    'common.popular': 'Popular',
    'common.featured': 'Featured',
    'common.bestseller': 'Bestseller',
    'common.out_of_stock': 'Out of Stock',
    'common.in_stock': 'In Stock',
    'common.add_to_cart': 'Add to Cart',
    'common.buy_now': 'Buy Now',
    'common.learn_more': 'Learn More',
    'common.read_more': 'Read More',
    'common.view_all': 'View All',
    'common.show_more': 'Show More',
    'common.show_less': 'Show Less',
  },
  th: {
    // Navigation
    'nav.home': 'หน้าหลัก',
    'nav.supplements': 'อาหารเสริม',
    'nav.ai_consultant': 'ที่ปรึกษา AI',
    'nav.blog': 'บล็อก',
    'nav.affiliate': 'พันธมิตร',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.sign_in': 'เข้าสู่ระบบ',
    'nav.logout': 'ออกจากระบบ',
    'nav.profile': 'โปรไฟล์',
    
    // AI Consultant Page
    'ai.title': 'ที่ปรึกษา AI',
    'ai.subtitle': 'อาหารเสริม',
    'ai.description': 'รับคำแนะนำอาหารเสริมเฉพาะบุคคลตามเป้าหมายสุขภาพและความต้องการของคุณ ที่ปรึกษา AI ของเราจะช่วยคุณค้นหาผลิตภัณฑ์ที่เหมาะสมสำหรับการดูแลสุขภาพของคุณ',
    'ai.consultant_name': 'ที่ปรึกษา AI',
    'ai.consultant_subtitle': 'การเลือกอาหารเสริมเฉพาะบุคคล',
    'ai.input_placeholder': 'อธิบายความต้องการของคุณ...',
    'ai.initial_message': 'สวัสดี! ฉันจะช่วยคุณค้นหาอาหารเสริมที่เหมาะสมสำหรับความต้องการของคุณ บอกฉันเกี่ยวกับปัญหาสุขภาพหรือเป้าหมายที่คุณต้องการบรรลุ?',
    
    // Footer
    'footer.brand_description': 'ผู้นำในการจำหน่ายอาหารเสริมธรรมชาติคุณภาพสูงเพื่อสุขภาพที่ดีขึ้นสำหรับคุณและครอบครัว',
    'footer.quick_links': 'ลิงก์ด่วน',
    'footer.all_products': 'สินค้าทั้งหมด',
    'footer.categories': 'หมวดหมู่',
    'footer.affiliate_program': 'โปรแกรมพันธมิตร',
    'footer.about_us': 'เกี่ยวกับเรา',
    'footer.customer_service': 'บริการลูกค้า',
    'footer.faq': 'คำถามที่พบบ่อย',
    'footer.return_policy': 'นโยบายการคืนสินค้า',
    'footer.shipping': 'การจัดส่ง',
    'footer.contact_us': 'ติดต่อเรา',
    'footer.copyright': '© 2024 SIAM HEALTHY สงวนลิขสิทธิ์',
    
    // Home Page
    'home.hero_title': 'เสี่ยม เฮลท์ธี่',
    'home.hero_subtitle': 'อาหารเสริมธรรมชาติพรีเมียม',
    'home.ai_recommendations_title': 'รับคำแนะนำเฉพาะบุคคล',
    'home.ai_recommendations_description': 'ที่ปรึกษา AI ของเราวิเคราะห์เป้าหมายสุขภาพของคุณและแนะนำอาหารเสริมที่เหมาะสมสำหรับความต้องการของคุณ รับคำแนะนำจากผู้เชี่ยวชาญในการค้นหาผลิตภัณฑ์ที่เหมาะสมสำหรับการดูแลสุขภาพของคุณ',
    'home.ai_personal_selection': '💊 การคัดเลือกเฉพาะบุคคล',
    'home.ai_goal_matching': '🎯 การจับคู่ตามเป้าหมาย',
    'home.ai_instant_recommendations': '⚡ คำแนะนำทันที',
    'home.start_ai_consultation': 'เริ่มการปรึกษา AI',
    'home.shop_supplements': 'ช้อปอาหารเสริม',
    'home.product_categories': 'หมวดหมู่สินค้า',
    'home.categories_description': 'เลือกหมวดหมู่ที่ตรงกับความต้องการด้านสุขภาพของคุณ',
    'home.featured_products': 'สินค้าแนะนำ',
    'home.featured_description': 'ผลิตภัณฑ์คุณภาพสูงที่ได้รับความนิยมจากลูกค้าของเรา',
    'home.all_products': 'สินค้าทั้งหมด',
    'home.latest_insights': 'ข้อมูลเชิงลึกด้านสุขภาพล่าสุด',
    'home.insights_description': 'คำแนะนำจากผู้เชี่ยวชาญจากนักโภชนาการ แพทย์ และผู้เชี่ยวชาญด้านสุขภาพ',
    'home.view_all_posts': 'ดูโพสต์ทั้งหมด',
    'home.view': 'ดู',
    'home.buy': 'ซื้อ',
    'home.read': 'อ่าน',
    
    // Categories
    'categories.beauty': 'ความงามและการดูแลป้องกันริ้วรอย',
    'categories.beauty_desc': 'สนับสนุนการเพิ่มความกระจ่างใสและป้องกันริ้วรอย',
    'categories.weight': 'ควบคุมน้ำหนักและสัดส่วน',
    'categories.weight_desc': 'สนับสนุนการเผาผลาญไขมันและเมแทบอลิซึม',
    'categories.vision': 'สุขภาพดวงตาและการมองเห็น',
    'categories.vision_desc': 'สนับสนุนการมองเห็นและปกป้องดวงตา',
    'categories.heart': 'สุขภาพหัวใจ',
    'categories.heart_desc': 'สนับสนุนความดันโลหิตและระบบหัวใจและหลอดเลือด',
    'categories.detox': 'ดีท็อกซ์และล้างพิษ',
    'categories.detox_desc': 'ล้างพิษร่างกายและกำจัดสารพิษ',
    
    // Products Page
    'products.title': 'อาหารเสริมเพื่อสุขภาพธรรมชาติ',
    'products.description': 'ค้นพบคอลเลกชันพรีเมียมของอาหารเสริมธรรมชาติของเรา',
    'products.search_placeholder': 'ค้นหาสินค้า...',
    'products.filter_category': 'กรองตามหมวดหมู่',
    'products.all_categories': 'หมวดหมู่ทั้งหมด',
    'products.sort_by': 'เรียงตาม',
    'products.price_low_high': 'ราคา: ต่ำไปสูง',
    'products.price_high_low': 'ราคา: สูงไปต่ำ',
    'products.newest': 'ใหม่ล่าสุด',
    'products.popularity': 'ยอดนิยมสูงสุด',
    'products.no_products': 'ไม่พบสินค้า',
    'products.no_products_desc': 'ลองปรับเงื่อนไขการค้นหาหรือตัวกรอง',
    'products.clear_filters': 'ล้างตัวกรอง',
    'products.add_to_cart': 'เพิ่มลงตะกร้า',
    'products.view_details': 'ดูรายละเอียด',
    'products.reviews': 'รีวิว',
    
    // Cart Page
    'cart.title': 'ตะกร้าสินค้า',
    'cart.empty_title': 'ตะกร้าของคุณว่างเปล่า',
    'cart.empty_description': 'เพิ่มสินค้าลงในตะกร้าเพื่อดำเนินการช้อปปิ้งต่อ',
    'cart.continue_shopping': 'ช้อปปิ้งต่อ',
    'cart.clear_cart': 'ล้างตะกร้า',
    'cart.cart_items': 'รายการสินค้าในตะกร้า',
    'cart.quantity': 'จำนวน',
    'cart.remove': 'ลบ',
    'cart.subtotal': 'ยอดรวมย่อย',
    'cart.delivery': 'การจัดส่ง',
    'cart.total': 'ยอดรวมทั้งหมด',
    'cart.free_delivery': 'จัดส่งฟรี',
    'cart.checkout': 'ดำเนินการชำระเงิน',
    'cart.shipping_info': 'ข้อมูลการจัดส่ง',
    'cart.first_name': 'ชื่อ',
    'cart.last_name': 'นามสกุล',
    'cart.email': 'อีเมล',
    'cart.phone': 'โทรศัพท์',
    'cart.address': 'ที่อยู่',
    'cart.city': 'เมือง',
    'cart.postal_code': 'รหัสไปรษณีย์',
    'cart.country': 'ประเทศ',
    'cart.payment_method': 'วิธีการชำระเงิน',
    'cart.delivery_method': 'วิธีการจัดส่ง',
    'cart.standard_delivery': 'จัดส่งมาตรฐาน',
    'cart.express_delivery': 'จัดส่งด่วน',
    'cart.pickup': 'รับเอง',
    'cart.place_order': 'สั่งซื้อ',
    'cart.required': 'จำเป็น',
    
    // About Page
    'about.hero_title': 'พันธมิตรที่เชื่อถือได้',
    'about.hero_subtitle': 'ในด้านสุขภาพธรรมชาติ',
    'about.hero_description': 'เราเป็นผู้เชี่ยวชาญด้านอาหารเสริมธรรมชาติที่มุ่งมั่นในการให้ผลิตภัณฑ์คุณภาพสูงเพื่อสุขภาพที่ดีขึ้นสำหรับคุณและครอบครัว ด้วยประสบการณ์กว่า 5 ปี',
    'about.mission_title': 'พันธกิจของเรา',
    'about.mission_description': 'เพื่อให้อาหารเสริมธรรมชาติคุณภาพสูงที่ปลอดภัย มีประสิทธิภาพ และเข้าถึงได้ เพื่อช่วยให้ทุกคนบรรลุสุขภาพและคุณภาพชีวิตที่ดีขึ้น',
    'about.vision_title': 'วิสัยทัศน์ของเรา',
    'about.vision_description': 'เพื่อเป็นแบรนด์อาหารเสริมธรรมชาติที่เชื่อถือได้ที่สุดในประเทศไทย และขยายไปยังตลาดต่างประเทศในอนาคต โดยยึดหลักการพัฒนาอย่างยั่งยืน',
    'about.values_title': 'คุณค่าของเรา',
    'about.values_description': 'หลักการและคุณค่าที่เป็นรากฐานของการทำงานและการให้บริการของเรา',
    'about.natural_title': '100% ธรรมชาติ',
    'about.natural_description': 'เราใช้เฉพาะส่วนผสมธรรมชาติคุณภาพสูง ปราศจากสารเคมีที่เป็นอันตราย',
    'about.standards_title': 'มาตรฐานสากล',
    'about.standards_description': 'ผลิตภัณฑ์ทั้งหมดได้รับการรับรองด้วยมาตรฐาน GMP, FDA และ ISO',
    'about.care_title': 'การดูแลลูกค้า',
    'about.care_description': 'เราเข้าใจความต้องการของลูกค้าแต่ละคนและมุ่งมั่นให้บริการที่ดีที่สุด',
    'about.expert_title': 'ทีมผู้เชี่ยวชาญ',
    'about.expert_description': 'ทีมงานที่มีความรู้ด้านโภชนาการและสุขภาพพร้อมให้คำปรึกษา',
    'about.achievements_title': 'ความสำเร็จที่เราภูมิใจ',
    'about.achievements_description': 'ตัวเลขที่สะท้อนถึงความสำเร็จและความไว้วางใจของลูกค้า',
    'about.customers': 'ลูกค้าที่พึงพอใจ',
    'about.experience': 'ปีประสบการณ์',
    'about.products_count': 'ผลิตภัณฑ์คุณภาพ',
    'about.satisfaction': 'อัตราความพึงพอใจ',
    'about.certifications_title': 'การรับรองมาตรฐาน',
    'about.certifications_description': 'ผลิตภัณฑ์ของเราได้รับการรับรองจากองค์กรที่เชื่อถือได้',
    'about.journey_title': 'เส้นทางการเติบโตของเรา',
    'about.journey_description': 'ประวัติและความก้าวหน้าของเราตลอดหลายปีที่ผ่านมา',
    'about.why_choose_title': 'ทำไมต้องเลือกเรา',
    'about.why_choose_description': 'เหตุผลที่ลูกค้ากว่า 10,000 คนไว้วางใจเรา',
    'about.trusted_quality': 'คุณภาพที่เชื่อถือได้',
    'about.trusted_quality_desc': 'ทุกผลิตภัณฑ์ผ่านการควบคุมคุณภาพอย่างเข้มงวดและได้รับการรับรองตามมาตรฐานสากล',
    'about.fast_delivery': 'บริการจัดส่งรวดเร็ว',
    'about.fast_delivery_desc': 'จัดส่งฟรีทั่วประเทศ รับประกันจัดส่งภายใน 1-2 วันทำการ พร้อมบริการติดตามพัสดุ',
    'about.expert_consultation': 'ทีมผู้เชี่ยวชาญพร้อมให้คำปรึกษา',
    'about.expert_consultation_desc': 'เภสัชกรและนักโภชนาการพร้อมให้คำแนะนำการเลือกผลิตภัณฑ์ 24 ชั่วโมง',
    'about.cta_title': 'พร้อมเริ่มต้นการเดินทางสู่สุขภาพกับเราแล้วหรือยัง?',
    'about.cta_description': 'เข้าร่วมครอบครัว SIAM HEALTHY และสัมผัสการดูแลสุขภาพแบบธรรมชาติ',
    'about.shop_products': 'ช้อปสินค้า',
    'about.join_affiliate': 'เข้าร่วมโปรแกรมพันธมิตร',
    
    // Affiliate Page
    'affiliate.hero_title': 'มาเป็นพันธมิตรกับเรา',
    'affiliate.hero_description': 'แบ่งปันอาหารเสริมธรรมชาติที่คุณเชื่อมั่น และรับค่าคอมมิชชั่นสูงสุด 25% จากทุกการขาย',
    'affiliate.start_earning': 'เริ่มสร้างรายได้วันนี้ - ฟรี!',
    'affiliate.why_partner_title': 'ทำไมต้องเป็นพันธมิตรกับเรา?',
    'affiliate.benefits_description': 'ทุกสิ่งที่คุณต้องการเพื่อประสบความสำเร็จในฐานะพันธมิตรของเรา',
    'affiliate.high_commission': 'ค่าคอมมิชชั่นสูง',
    'affiliate.high_commission_desc': 'รับสูงสุด 25% จากทุกการขายที่คุณทำ',
    'affiliate.full_support': 'การสนับสนุนเต็มรูปแบบ',
    'affiliate.full_support_desc': 'รับความช่วยเหลือจากทีมงานเฉพาะของเรา',
    'affiliate.free_products': 'ผลิตภัณฑ์ฟรี',
    'affiliate.free_products_desc': 'รับตัวอย่างผลิตภัณฑ์เพื่อทดสอบและรีวิว',
    'affiliate.how_it_works': 'วิธีการทำงาน',
    'affiliate.steps_description': 'เริ่มต้นใน 3 ขั้นตอนง่าย ๆ',
    'affiliate.step_apply': 'สมัคร',
    'affiliate.step_apply_desc': 'กรอกแบบฟอร์มง่าย ๆ ด้านล่าง',
    'affiliate.step_approved': 'รับการอนุมัติ',
    'affiliate.step_approved_desc': 'เราจะตรวจสอบและอนุมัติภายใน 2 วัน',
    'affiliate.step_earn': 'เริ่มสร้างรายได้',
    'affiliate.step_earn_desc': 'แบ่งปันลิงก์ของคุณและสร้างรายได้',
    'affiliate.join_program': 'เข้าร่วมโปรแกรมพันธมิตรของเรา',
    'affiliate.join_description': 'พร้อมเริ่มสร้างรายได้แล้วหรือยัง? ใช้เวลาไม่ถึง 2 นาที',
    'affiliate.your_name': 'ชื่อของคุณ',
    'affiliate.email_address': 'ที่อยู่อีเมล',
    'affiliate.promote_where': 'คุณจะโปรโมตที่ไหน?',
    'affiliate.choose_platform': 'เลือกแพลตฟอร์มของคุณ',
    'affiliate.agree_terms': 'ฉันยอมรับข้อกำหนดและเงื่อนไข',
    'affiliate.submit_application': 'ส่งใบสมัคร',
    'affiliate.submitting': 'กำลังส่ง...',
    'affiliate.quick_questions': 'คำถามด่วน',
    'affiliate.how_much_earn': 'ฉันสามารถสร้างรายได้ได้เท่าไหร่?',
    'affiliate.how_much_earn_answer': 'คุณได้รับค่าคอมมิชชั่นสูงสุด 25% จากทุกการขาย ยิ่งขายมากค่าคอมมิชชั่นยิ่งสูง',
    'affiliate.when_paid': 'เมื่อไหร่ที่ฉันจะได้รับเงิน?',
    'affiliate.when_paid_answer': 'ค่าคอมมิชชั่นจะจ่ายทุกเดือนในวันที่ 15 โดยตรงเข้าบัญชีธนาคารของคุณ',
    'affiliate.really_free': 'ฟรีจริง ๆ หรือ?',
    'affiliate.really_free_answer': 'ใช่! ไม่มีค่าธรรมเนียมในการเข้าร่วม คุณเริ่มสร้างรายได้ได้ทันทีหลังจากได้รับการอนุมัติ',
    
    // Blog Page
    'blog.title': 'บล็อกสุขภาพและความเป็นอยู่ที่ดี',
    'blog.description': 'ข้อมูลเชิงลึกจากผู้เชี่ยวชาญเกี่ยวกับการใช้ชีวิตสุขภาพดี การป้องกันโรค และสุขภาพธรรมชาติจากนักโภชนาการ แพทย์ และผู้เชี่ยวชาญการแพทย์แผนไทย',
    'blog.all': 'ทั้งหมด',
    'blog.read_more': 'อ่านเพิ่มเติม',
    'blog.min_read': 'นาทีในการอ่าน',
    'blog.back_to_blog': 'กลับไปที่บล็อก',
    'blog.related_articles': 'บทความที่เกี่ยวข้อง',
    'blog.post_not_found': 'ไม่พบโพสต์',
    'blog.post_not_found_desc': 'โพสต์บล็อกที่คุณกำลังมองหาไม่มีอยู่',
    
    // Profile Page  
    'profile.title': 'โปรไฟล์ของฉัน',
    'profile.personal_info': 'ข้อมูลส่วนตัว',
    'profile.order_history': 'ประวัติการสั่งซื้อ',
    'profile.settings': 'การตั้งค่า',
    'profile.save_changes': 'บันทึกการเปลี่ยนแปลง',
    'profile.no_orders': 'ยังไม่มีคำสั่งซื้อ',
    'profile.no_orders_desc': 'เริ่มช้อปปิ้งเพื่อดูคำสั่งซื้อของคุณที่นี่',
    
    // Auth Page
    'auth.sign_in': 'เข้าสู่ระบบ',
    'auth.sign_up': 'สมัครสมาชิก',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.confirm_password': 'ยืนยันรหัสผ่าน',
    'auth.forgot_password': 'ลืมรหัสผ่าน?',
    'auth.no_account': 'ยังไม่มีบัญชี?',
    'auth.have_account': 'มีบัญชีแล้ว?',
    
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.view': 'ดู',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.sort': 'เรียง',
    'common.previous': 'ก่อนหน้า',
    'common.next': 'ถัดไป',
    'common.page': 'หน้า',
    'common.of': 'จาก',
    'common.items': 'รายการ',
    'common.item': 'รายการ',
    'common.total': 'ยอดรวม',
    'common.subtotal': 'ยอดรวมย่อย',
    'common.discount': 'ส่วนลด',
    'common.free': 'ฟรี',
    'common.new': 'ใหม่',
    'common.popular': 'ยอดนิยม',
    'common.featured': 'แนะนำ',
    'common.bestseller': 'ขายดี',
    'common.out_of_stock': 'สินค้าหมด',
    'common.in_stock': 'มีสินค้า',
    'common.add_to_cart': 'เพิ่มลงตะกร้า',
    'common.buy_now': 'ซื้อเลย',
    'common.learn_more': 'เรียนรู้เพิ่มเติม',
    'common.read_more': 'อ่านเพิ่มเติม',
    'common.view_all': 'ดูทั้งหมด',
    'common.show_more': 'แสดงเพิ่มเติม',
    'common.show_less': 'แสดงน้อยลง',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
