-- Remove existing products
DELETE FROM products;

-- Insert new 15 products
INSERT INTO products (id, name, price, original_price, image_url, rating, reviews_count, description, keywords, category, benefits, in_stock, sort_order, line_url) VALUES
(1, 'Lylac — Natural Beauty & Detox Capsules', '฿890', '฿1,290', '/lovable-uploads/Lylac.webp', 4.8, 145, 'Natural formula for beauty enhancement and body detoxification', '["beauty", "detox", "cleanse", "skin health", "natural"]', 'beauty-supplement', '["Improves skin quality", "Detoxifies body", "Natural ingredients"]', 15, 1, 'https://lin.ee/lylac123'),
(2, 'Genesis — Immune & Energy Boost Capsules', '฿950', '฿1,350', '/lovable-uploads/Genesis.webp', 4.9, 167, 'Premium immune system support and energy enhancement', '["immune", "energy", "vitality", "health", "boost"]', 'immune-support', '["Boosts immunity", "Increases energy", "Supports overall health"]', 12, 2, 'https://lin.ee/genesis123'),
(3, 'T-chrome — Men''s Health & Vitality Capsules', '฿1,100', '฿1,550', '/lovable-uploads/T-chrome.webp', 4.8, 198, 'Specialized formula for men''s health and performance', '["mens health", "vitality", "testosterone", "energy", "performance"]', 'mens-health', '["Supports male vitality", "Enhances performance", "Natural testosterone support"]', 10, 3, 'https://lin.ee/tchrome123'),
(4, 'Helmina — Digestive Health & Detox Capsules', '฿870', '฿1,250', '/lovable-uploads/Helmina.webp', 4.7, 132, 'Comprehensive digestive system support and cleansing', '["digestive", "detox", "gut health", "cleanse", "wellness"]', 'digestive-health', '["Improves digestion", "Cleanses system", "Supports gut health"]', 18, 4, 'https://lin.ee/helmina123'),
(5, 'Geralox — Joint & Energy Support Capsules', '฿990', '฿1,420', '/lovable-uploads/Geralox.webp', 4.8, 156, 'Advanced joint support and energy enhancement formula', '["joint", "energy", "mobility", "flexibility", "vitality"]', 'joint-health', '["Supports joint health", "Increases flexibility", "Boosts energy"]', 14, 5, 'https://lin.ee/geralox123'),
(6, 'Onix — Weight Control & Fat Burning Capsules', '฿890', '฿1,575', '/lovable-uploads/Onix.webp', 4.8, 175, 'Effective complex for weight control and fat burning', '["weight loss", "fat burning", "metabolism", "slimming", "diet"]', 'weight-loss', '["Boosts metabolism", "Burns fat", "Suppresses appetite"]', 8, 6, 'https://lin.ee/8OfKkNJ'),
(7, 'Turbine — Energy & Performance Capsules', '฿920', '฿1,320', '/lovable-uploads/Turbine.webp', 4.9, 189, 'High-performance energy and stamina enhancement', '["energy", "performance", "stamina", "vitality", "endurance"]', 'energy-vitality', '["Increases energy", "Enhances stamina", "Improves performance"]', 16, 7, 'https://lin.ee/turbine123'),
(8, 'Carthisin — Joint Health & Mobility Capsules', '฿940', '฿1,380', '/lovable-uploads/Carthisin.webp', 4.8, 143, 'Premium cartilage support and joint mobility formula', '["joint", "cartilage", "mobility", "flexibility", "bone health"]', 'joint-health', '["Supports cartilage", "Improves mobility", "Reduces joint discomfort"]', 11, 8, 'https://lin.ee/carthisin123'),
(9, 'Andicellix — Digestive Wellness & Detox Capsules', '฿880', '฿1,280', '/lovable-uploads/Andicellix.webp', 4.7, 138, 'Complete digestive support and body cleansing system', '["digestive", "detox", "wellness", "gut health", "cleanse"]', 'digestive-health', '["Supports digestion", "Detoxifies body", "Improves gut health"]', 13, 9, 'https://lin.ee/andicellix123'),
(10, 'S-Complex — Anti-Aging & Skin Firming Capsules', '฿999', '฿1,470', '/lovable-uploads/S-Complex.webp', 4.9, 198, 'Complex for anti-aging, skin brightening and firming', '["anti-aging", "skin", "beauty", "firming", "collagen"]', 'beauty-supplement', '["Reduces wrinkles", "Improves skin firmness", "Brightens pigmentation"]', 9, 10, 'https://lin.ee/gGN1rXh'),
(11, 'Philola — Eye Health & Vision Support Capsules', '฿1,190', '฿1,400', '/lovable-uploads/Philola.webp', 4.9, 167, 'Comprehensive eye health and vision improvement support', '["vision", "eyes", "eye health", "sight", "visual"]', 'eye-health', '["Improves visual acuity", "Reduces eye fatigue", "Protects from blue light"]', 15, 11, 'https://lin.ee/ujbBjYd'),
(12, 'Black Rhino — Men''s Power & Vitality Capsules', '฿1,150', '฿1,650', '/lovable-uploads/Black-Rhino.webp', 4.9, 212, 'Ultimate men''s health and performance enhancement', '["mens health", "power", "vitality", "performance", "energy"]', 'mens-health', '["Enhances male vitality", "Boosts performance", "Increases energy"]', 7, 12, 'https://lin.ee/blackrhino123'),
(13, 'Oclarizin — Eye Health & Vision Support Capsules', '฿930', '฿1,330', '/lovable-uploads/Oclarizin.webp', 4.9, 143, 'Premium formula for vision support and eye health', '["vision", "eyes", "eye health", "cataract", "retina"]', 'eye-health', '["Protects retina", "Prevents cataracts", "Improves night vision"]', 10, 13, 'https://lin.ee/jK1TEb0'),
(14, 'Elsie — Anti-Aging & Beauty Enhancement Capsules', '฿960', '฿1,390', '/lovable-uploads/Elsie.webp', 4.8, 154, 'Advanced anti-aging and beauty enhancement formula', '["anti-aging", "beauty", "skin", "youth", "collagen"]', 'anti-aging', '["Reduces aging signs", "Enhances beauty", "Improves skin texture"]', 12, 14, 'https://lin.ee/elsie123'),
(15, 'Backpro — Back & Joint Support Capsules', '฿970', '฿1,420', '/lovable-uploads/Backpro.webp', 4.8, 161, 'Specialized back and spine health support formula', '["back health", "joint", "spine", "mobility", "pain relief"]', 'joint-health', '["Supports back health", "Improves spine mobility", "Reduces discomfort"]', 14, 15, 'https://lin.ee/backpro123');