// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbpxjelgpviavsvuxluq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicHhqZWxncHZpYXZzdnV4bHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzgyMTksImV4cCI6MjA2NTgxNDIxOX0.tgYH31UV_dMwr8cy6aOhEbXM3TrJ6T63BEWyl0U9hEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);